import { test, expect, type Page, type Route } from '@playwright/test'

// Controlled network responses are confined to browser tests; production uses the API.
async function controlledCatalog(page: Page) {
  const pending: Route[] = []
  await page.route('https://**/*', async route => {
    if (new URL(route.request().url()).pathname.includes('/v1/public/')) pending.push(route)
    else await route.abort()
  })
  const finish = (route: Route, status = 200) => route.fulfill({ status, contentType: 'application/json', body: JSON.stringify(status === 200 ? { data: [] } : { error: { message: 'Error de prueba' } }) })
  return { pending, finish }
}

test('one overlay for concurrent requests, initial load, cached navigation and reload', async ({ page }) => {
  const { pending, finish } = await controlledCatalog(page)
  await page.goto('/')
  const dialog = page.getByRole('dialog', { name: 'Cargando experiencia' })
  await expect(dialog).toHaveCount(1)
  await expect.poll(() => pending.length).toBe(3)
  await expect(page.getByRole('progressbar')).not.toHaveAttribute('aria-valuenow')
  await expect(page.locator('#root')).toHaveJSProperty('inert', true)
  await expect(dialog).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(dialog).toBeFocused()
  await page.screenshot({ path: 'test-results/loading-desktop.png' })
  await finish(pending[0])
  await finish(pending[1])
  await expect(dialog).toBeVisible()
  await finish(pending[2])
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('#root')).toHaveJSProperty('inert', false)
  await expect(page.locator('body')).not.toHaveCSS('position', 'fixed')
  await page.getByRole('link', { name: 'Ver todas', exact: true }).first().click()
  await expect(page).toHaveURL(/motocicletas$/)
  await expect(dialog).toHaveCount(0)
  expect(pending).toHaveLength(3)
  await page.reload()
  await expect(dialog).toBeVisible()
  await expect.poll(() => pending.length).toBe(6)
  await Promise.all(pending.slice(3).map(route => finish(route)))
  await expect(dialog).toHaveCount(0)
  await expect(page.getByText('El catálogo está vacío.', { exact: false })).toBeVisible()
})

test('failure closes immediately, retry locks background and restores scroll and focus', async ({ page }) => {
  const { pending, finish } = await controlledCatalog(page)
  await page.goto('/')
  await expect.poll(() => pending.length).toBe(3)
  await finish(pending[0], 500)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const retry = page.getByRole('button', { name: 'Reintentar', exact: true })
  await expect(retry).toBeVisible()
  // Other requests may still be pending when one fails. Complete them before retry.
  await Promise.all(pending.slice(1).map(route => finish(route)))
  await retry.scrollIntoViewIfNeeded()
  await retry.focus()
  await page.evaluate(() => { document.documentElement.style.scrollBehavior = 'auto' })
  const before = await page.evaluate(() => window.scrollY)
  await retry.click()
  await expect(page.getByRole('dialog')).toBeFocused()
  await expect(page.locator('body')).toHaveCSS('position', 'fixed')
  await expect.poll(() => pending.length).toBe(6)
  await Promise.all(pending.slice(3).map(route => finish(route)))
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('main')).toBeFocused()
  expect(await page.evaluate(() => window.scrollY)).toBe(before)
})

test('mobile layout and reduced motion, direct brand route stops loading on error', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const { pending, finish } = await controlledCatalog(page)
  await page.goto('/ktm')
  const dialog = page.getByRole('dialog', { name: 'Cargando experiencia' })
  await expect(dialog).toBeVisible()
  await expect(page.locator('.loading-progress')).toHaveCSS('animation-name', 'none')
  await expect(page.locator('.loading-spinner')).toHaveCSS('animation-name', 'none')
  const box = await dialog.boundingBox()
  expect(box?.width).toBeLessThanOrEqual(350)
  await page.screenshot({ path: 'test-results/loading-mobile.png' })
  await expect.poll(() => pending.length).toBe(3)
  await finish(pending[2], 500)
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Reintentar', exact: true })).toBeVisible()
  await Promise.all(pending.slice(0, 2).map(route => finish(route)))
})
